# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
cache: packages
warnings_are_errors: true

# Build matrix
jobs:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel

# Environment variables set for all builds
env:
  global:
  # Don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
